title: MuSigma
email: boards@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming mostly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musigma.blog" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title:output_ext
author: Matt Sicker
twitter_username: jvz
github_username:  jvz
exclude: 
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor/bundle"
  - ".github"
timezone: "America/Chicago"
encoding: "utf-8"
markdown: kramdown
theme: jekyll-theme-nn
plugins:
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-category-pages
category_path: category
category_layout: category_index.html
