# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MuSigma
email: boards@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming mostly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musigma.blog" # the base hostname & protocol for your site
twitter_username: jvz
github_username:  jvz
exclude: 
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor/bundle"
timezone: "America/Chicago"
encoding: "utf-8"

# Build settings
markdown: kramdown

plugins:
  - jekyll-avatar

# Default post settings
defaults:
  -
    scope:
      path: ""
    values:
      author: "Matt Sicker"
