name: site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build Jekyll Site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Deploy Tarball
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KNOWN_HOSTS" >.github/known_hosts
        echo "$SSH_KEY" >.github/id_ed25519
        chmod 600 .github/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add .github/id_ed25519
        tar -czvf - -C _site . | ssh musigma_musigmablog@ssh.phx.nearlyfreespeech.net 'tar -xzvf -'
