name: site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache Dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install --path vendor/bundle
    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build
    - name: Deploy Tarball
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir $HOME/.ssh
        echo "$SSH_KNOWN_HOSTS" >$HOME/.ssh/known_hosts
        echo "$SSH_KEY" >$HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add $HOME/.ssh/id_ed25519
        tar -czvf - -C _site . | ssh musigma_musigmablog@ssh.musigma.blog 'tar -xzvf -'
