name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Deploy
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KNOWN_HOSTS" >$HOME/.ssh/known_hosts
        echo "$SSH_KEY" >$HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
        #eval "$(ssh-agent -s)"
        #ssh-add .github/workflows/ssh_key
        tar -czvf - -C _site . | ssh musigma_musigmablog@ssh.phx.nearlyfreespeech.net 'tar -xzvf -'
