name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_KNOWN_HOSTS: ${ secrets.SSH_KNOWN_HOSTS }}
      run: |
        echo "$SSH_KNOWN_HOSTS" .github/workflows/known_hosts
        echo "$SSH_KEY" >.github/workflows/ssh_key
        chmod 600 .github/workflows/ssh_key
        eval "$(ssh-agent -s)"
        ssh-add .github/workflows/ssh_key
        tar -czvf - -C _site . | ssh -T -o UserKnownHostsFile=$PWD/.github/workflows/known_hosts musigma_musigmablog@ssh.phx.nearlyfreespeech.net 'tar -xzvf -'
